// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgyEd8FfqjYyzSWCwVfYmZzzvszVgBYFs',
    appId: '1:27232363866:android:ccbf4877e319b65e553f63',
    messagingSenderId: '27232363866',
    projectId: 'flutter-chat-app-b9e19',
    storageBucket: 'flutter-chat-app-b9e19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2zk1casSyvWLcgMT8b_1lIl8o-Dm2UYE',
    appId: '1:27232363866:ios:6c11d3e87892e1a6553f63',
    messagingSenderId: '27232363866',
    projectId: 'flutter-chat-app-b9e19',
    storageBucket: 'flutter-chat-app-b9e19.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVE18LxDy_f7mMoVXYP2bIJKlEIvNrLvM',
    appId: '1:27232363866:web:4b1b684f8b908866553f63',
    messagingSenderId: '27232363866',
    projectId: 'flutter-chat-app-b9e19',
    authDomain: 'flutter-chat-app-b9e19.firebaseapp.com',
    storageBucket: 'flutter-chat-app-b9e19.firebasestorage.app',
  );

}